const IMAGES = {
  LOAD: 'IMAGES_LOAD',
  LOAD_IMAGES_SUCCESS: 'LOAD_IMAGES_SUCCESS',
  LOAD_IMAGES_FAIL: 'LOAD_IMAGES_FAIL',
};

const STATS = {
  LOAD: 'STATS_LOAD',
  LOAD_STATS_SUCCESS: 'LOAD_STATS_SUCCESS',
  LOAD_STATS_FAIL: 'LOAD_STATS_FAIL',
};

export { IMAGES, STATS };
